// "Ellenőrzött Felújítás" — a Back Market "The Back Market Promise" oldala adta az
// ötletet a formára (jelvények + folyamat + minőségi fokozatok + utánunk is számíthatsz ránk),
// de a TARTALOM végig a mi valódi, belső tesztelő-kérdőívünkből (REFURB_INSPECTION_QUESTIONS,
// CONDITION_GRADES — lásd src/lib/utils.js) jön, semmi kitalált szám vagy állítás nincs benne.

export const QUALITY_CONTENT = {
  hu: {
    title: "Ellenőrzött Felújítás — Telefonos",
    metaDesc: "Mit jelent nálunk, hogy egy telefon \"felújított\"? 8 pontos ellenőrzés, feltüntetett akkuegészség, garancia a minőségi fokozat szerint.",
    eyebrow: "Ellenőrzött Felújítás",
    h1: "Mit jelent nálunk, hogy egy telefon felújított?",
    intro: "Nem csak letöröljük és feltesszük polcra. Minden hozzánk kerülő használt telefon ugyanazon a 8 pontos vizsgálaton megy át, mielőtt eladásra kínáljuk — ez alapján döntjük el a minőségi besorolást, a garanciát, és ez alapján írjuk fel az akkuegészséget minden termékoldalra.",
    badges: [
      { title: "8 pontos ellenőrzés", sub: "Minden felújított telefonon, boltban, nem külső partnernél" },
      { title: "Akkuegészség kiírva", sub: "Nem becslés — minden termékoldalon ott a %" },
      { title: "1–6 hónap garancia", sub: "A minőségi fokozattól függően" },
      { title: "14 napos elállás", sub: "Indoklás nélkül, törvény szerint" },
    ],
    checklistTitle: "A 8 pont, amit minden telefonon megnézünk",
    checklistIntro: "Ez pontosan az a kérdéssor, amit a szervizesünk kitölt minden bejövő telefonnál — nem marketing-lista, ez fut nálunk a háttérben.",
    checklist: [
      { title: "Bekapcsol és stabilan fut", desc: "Ha ezen elakad, a telefon nem kerül polcra, amíg meg nem javítjuk." },
      { title: "Kijelző kozmetikai állapota", desc: "Kifogástalantól a látható karcokig — ez befolyásolja a minőségi fokozatot." },
      { title: "Hátlap / keret állapota", desc: "Horpadás, kopás, karcok — ugyanúgy beleszámít a besorolásba." },
      { title: "Akkuegészség", desc: "Megmérjük, és a %-ot mindig feltüntetjük a termékoldalon." },
      { title: "Kamera(k) működése", desc: "Éles kép, minden kamera — ha nem, nem kerül eladásra javítás nélkül." },
      { title: "Gombok, töltőcsatlakozó, hangszóró", desc: "Mindegyik fizikai elem tesztelve." },
      { title: "Ujjlenyomat / Face ID", desc: "Ha a modellen van ilyen, ellenőrizzük, hogy működik-e." },
      { title: "Hálózatfüggetlenség", desc: "Megnézzük, nincs-e egy szolgáltatóhoz kötve a készülék." },
    ],
    gradesTitle: "Minőségi fokozatok — ez dönti el a garanciát",
    gradesIntro: "A fenti 8 pont alapján soroljuk be a telefont, és ez határozza meg, mennyi garanciát adunk rá.",
    grades: [
      { label: "Újszerű", warranty: "6 hónap garancia", desc: "Kifogástalan vagy szinte észrevehetetlen kozmetikai állapot, minden funkció hibátlan, jó akkuegészség." },
      { label: "Nagyon jó", warranty: "3 hónap garancia", desc: "Használatra utaló, de nem zavaró apró nyomok lehetnek rajta, minden funkció rendben." },
      { label: "Jó", warranty: "1 hónap garancia", desc: "Látható használati nyomok, de teljesen működőképes — ezért árban is ez a legkedvezőbb kategória." },
    ],
    gradesNote: "Amit sosem teszünk polcra: olyan telefont, ami nem kapcsol be, nem fut stabilan, vagy amin repedt/törött a kijelző, hátlap, kamera — ezeket előbb megjavítjuk, vagy alkatrésznek/bevonásra használjuk.",
    afterTitle: "Ami az eladás után jár",
    after: [
      { title: "Garancia a készülékre és az alkatrészekre", desc: "A minőségi fokozat szerinti időtartamra — a részletek a garanciajegyeden." },
      { title: "14 napos elállási jog", desc: "Indoklás nélkül visszahozhatod, ha mégsem az igazi. Részletek az ÁSZF-ben." },
      { title: "A szerviz is a miénk", desc: "Ha garanciális ügy adódik, nem küldünk sehova — helyben, nálunk oldjuk meg." },
      { title: "Valós vásárlói vélemények", desc: "Amit a korábbi vásárlóink mondanak, azt olvashatod is, nem csak halljuk mi." },
    ],
    ctaText: "Nézd meg, mi van most raktáron",
    ctaHref: "/",
  },
  ro: {
    title: "Reconditionare Verificată — Telefonos",
    metaDesc: "Ce înseamnă la noi ca un telefon să fie \"reconditionat\"? Verificare în 8 puncte, stare baterie afișată, garanție în funcție de categoria de calitate.",
    eyebrow: "Reconditionare Verificată",
    h1: "Ce înseamnă la noi ca un telefon să fie reconditionat?",
    intro: "Nu doar îl ștergem și îl punem pe raft. Fiecare telefon folosit care ajunge la noi trece prin aceeași verificare în 8 puncte înainte să fie pus la vânzare — pe baza acesteia stabilim categoria de calitate, garanția, și starea bateriei afișată pe fiecare pagină de produs.",
    badges: [
      { title: "Verificare în 8 puncte", sub: "La fiecare telefon reconditionat, în magazin, nu la un partener extern" },
      { title: "Starea bateriei afișată", sub: "Nu o estimare — procentul apare pe fiecare pagină de produs" },
      { title: "Garanție 1–6 luni", sub: "În funcție de categoria de calitate" },
      { title: "14 zile drept de retur", sub: "Fără motivare, conform legii" },
    ],
    checklistTitle: "Cele 8 puncte pe care le verificăm la fiecare telefon",
    checklistIntro: "Acesta este exact chestionarul pe care îl completează colegul din service la fiecare telefon primit — nu e o listă de marketing, chiar rulează la noi.",
    checklist: [
      { title: "Pornește și funcționează stabil", desc: "Dacă eșuează aici, telefonul nu ajunge pe raft până nu e reparat." },
      { title: "Starea cosmetică a ecranului", desc: "De la impecabil la zgârieturi vizibile — influențează categoria de calitate." },
      { title: "Starea capacului / ramei", desc: "Îndoituri, uzură, zgârieturi — contează la fel în clasificare." },
      { title: "Starea bateriei", desc: "O măsurăm și afișăm procentul mereu pe pagina de produs." },
      { title: "Funcționarea camerei/camerelor", desc: "Imagine clară, toate camerele — altfel nu e vândut fără reparație." },
      { title: "Butoane, conector de încărcare, difuzor", desc: "Fiecare element fizic e testat." },
      { title: "Amprentă / Face ID", desc: "Dacă modelul are, verificăm dacă funcționează." },
      { title: "Independență de rețea", desc: "Verificăm să nu fie blocat la un operator." },
    ],
    gradesTitle: "Categorii de calitate — de aici pornește garanția",
    gradesIntro: "Pe baza celor 8 puncte de mai sus clasificăm telefonul, iar asta determină garanția oferită.",
    grades: [
      { label: "Ca nou", warranty: "6 luni garanție", desc: "Stare cosmetică impecabilă sau aproape imperceptibilă, toate funcțiile perfecte, baterie bună." },
      { label: "Foarte bun", warranty: "3 luni garanție", desc: "Pot exista urme minore de utilizare, dar nederanjante, toate funcțiile funcționează." },
      { label: "Bun", warranty: "1 lună garanție", desc: "Urme vizibile de utilizare, dar complet funcțional — de aceea e și cea mai avantajoasă categorie de preț." },
    ],
    gradesNote: "Ce nu punem niciodată pe raft: un telefon care nu pornește, nu funcționează stabil, sau are ecranul/capacul/camera crăpate — pe acestea le reparăm întâi, sau le folosim pentru piese.",
    afterTitle: "Ce primești după cumpărare",
    after: [
      { title: "Garanție pentru telefon și piese", desc: "Pe durata corespunzătoare categoriei de calitate — detaliile sunt pe certificatul de garanție." },
      { title: "14 zile drept de retur", desc: "Poți returna fără motivare dacă nu ți se potrivește. Detalii în Termeni și condiții." },
      { title: "Service-ul e tot al nostru", desc: "Dacă apare o problemă în garanție, nu trimitem nicăieri — rezolvăm local, la noi." },
      { title: "Recenzii reale de la clienți", desc: "Poți citi ce spun clienții noștri anteriori, nu doar ce spunem noi." },
    ],
    ctaText: "Vezi ce avem acum în stoc",
    ctaHref: "/ro/telefoane",
  },
};
